# Generated by Django 2.1.3 on 2018-11-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('alert_time', models.TimeField()),
                ('parent_task_id', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
